/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as RtmeRouteImport } from './routes/rtme'
import { Route as SynthocracyRouteImport } from './routes/synthocracy'
import { Route as UdsRouteImport } from './routes/uds'
import { Route as WeaverRouteImport } from './routes/weaver'
import { Route as WitnessRouteImport } from './routes/witness'
import { Route as WorthRouteImport } from './routes/worth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const RtmeRoute = RtmeRouteImport.update({
  id: '/rtme',
  path: '/rtme',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthocracyRoute = SynthocracyRouteImport.update({
  id: '/synthocracy',
  path: '/synthocracy',
  getParentRoute: () => rootRouteImport,
} as any)
const UdsRoute = UdsRouteImport.update({
  id: '/uds',
  path: '/uds',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaverRoute = WeaverRouteImport.update({
  id: '/weaver',
  path: '/weaver',
  getParentRoute: () => rootRouteImport,
} as any)
const WitnessRoute = WitnessRouteImport.update({
  id: '/witness',
  path: '/witness',
  getParentRoute: () => rootRouteImport,
} as any)
const WorthRoute = WorthRouteImport.update({
  id: '/worth',
  path: '/worth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/mirror': typeof MirrorRoute
  '/rtme': typeof RtmeRoute
  '/synthocracy': typeof SynthocracyRoute
  '/uds': typeof UdsRoute
  '/weaver': typeof WeaverRoute
  '/witness': typeof WitnessRoute
  '/worth': typeof WorthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/mirror': typeof MirrorRoute
  '/rtme': typeof RtmeRoute
  '/synthocracy': typeof SynthocracyRoute
  '/uds': typeof UdsRoute
  '/weaver': typeof WeaverRoute
  '/witness': typeof WitnessRoute
  '/worth': typeof WorthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/mirror': typeof MirrorRoute
  '/rtme': typeof RtmeRoute
  '/synthocracy': typeof SynthocracyRoute
  '/uds': typeof UdsRoute
  '/weaver': typeof WeaverRoute
  '/witness': typeof WitnessRoute
  '/worth': typeof WorthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/mirror'
    | '/rtme'
    | '/synthocracy'
    | '/uds'
    | '/weaver'
    | '/witness'
    | '/worth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/mirror'
    | '/rtme'
    | '/synthocracy'
    | '/uds'
    | '/weaver'
    | '/witness'
    | '/worth'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/mirror'
    | '/rtme'
    | '/synthocracy'
    | '/uds'
    | '/weaver'
    | '/witness'
    | '/worth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  MirrorRoute: typeof MirrorRoute
  RtmeRoute: typeof RtmeRoute
  SynthocracyRoute: typeof SynthocracyRoute
  UdsRoute: typeof UdsRoute
  WeaverRoute: typeof WeaverRoute
  WitnessRoute: typeof WitnessRoute
  WorthRoute: typeof WorthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rtme': {
      id: '/rtme'
      path: '/rtme'
      fullPath: '/rtme'
      preLoaderRoute: typeof RtmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthocracy': {
      id: '/synthocracy'
      path: '/synthocracy'
      fullPath: '/synthocracy'
      preLoaderRoute: typeof SynthocracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uds': {
      id: '/uds'
      path: '/uds'
      fullPath: '/uds'
      preLoaderRoute: typeof UdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weaver': {
      id: '/weaver'
      path: '/weaver'
      fullPath: '/weaver'
      preLoaderRoute: typeof WeaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/witness': {
      id: '/witness'
      path: '/witness'
      fullPath: '/witness'
      preLoaderRoute: typeof WitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worth': {
      id: '/worth'
      path: '/worth'
      fullPath: '/worth'
      preLoaderRoute: typeof WorthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  MirrorRoute: MirrorRoute,
  RtmeRoute: RtmeRoute,
  SynthocracyRoute: SynthocracyRoute,
  UdsRoute: UdsRoute,
  WeaverRoute: WeaverRoute,
  WitnessRoute: WitnessRoute,
  WorthRoute: WorthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
